# Naive Bayes 실습

# 1. Gaussian Naive Bayes

- 데이터, 모듈 불러오기

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [2]:
import pandas as pd

In [3]:
iris = datasets.load_iris()
df_X=pd.DataFrame(iris.data)
df_Y=pd.DataFrame(iris.target)

In [4]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
df_X.head() #x변수 4개

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [6]:
df_Y.head()

0
0  0
1  0
2  0
3  0
4  0

- 모델 피팅

In [7]:
gnb=GaussianNB()
fitted=gnb.fit(iris.data,iris.target)
y_pred=fitted.predict(iris.data)

In [8]:
fitted.predict_proba(iris.data)[[1,48,51,100]]
#1열 0일 확률 1열1행 1번째 관측치가 0일 확률
#2열 1일확률 2열 1행 1번째 관측치가 1일 확률,2열 2행 48번째 관측치가 1일 확률

array([[1.00000000e+000, 1.51480769e-017, 2.34820051e-025],
       [1.00000000e+000, 2.63876217e-018, 2.79566024e-025],
       [7.27347795e-102, 9.45169639e-001, 5.48303606e-002],
       [3.23245181e-254, 6.35381031e-011, 1.00000000e+000]])

In [9]:
fitted.predict(iris.data)[[1,48,51,100]]

array([0, 0, 1, 2])

- Confusion matrix 구하기

In [10]:
from sklearn.metrics import confusion_matrix

In [11]:
confusion_matrix(iris.target,y_pred)
#1행 0인걸 50개 다맞춤
#2행 1인것을 47개 맞추고 3개 틀림
#3행 2인걸 47개 마추고 3개 틀림

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]], dtype=int64)

- Prior 설정하기

In [12]:
gnb2=GaussianNB(priors=[1/100,1/100,98/100])
fitted2=gnb2.fit(iris.data,iris.target)
y_pred2=fitted2.predict(iris.data)
confusion_matrix(iris.target,y_pred2)
#3번째가 맞출확률을 크게 했으므로98/100 3번쨰는 다맞춤 그러나 3번째꺼를 많이 마춘다고 2번째꺼 많이 틀림(3번째로 잘못맞춤) 

array([[50,  0,  0],
       [ 0, 33, 17],
       [ 0,  0, 50]], dtype=int64)

In [13]:
gnb2=GaussianNB(priors=[1/100,98/100,1/100])
fitted2=gnb2.fit(iris.data,iris.target)
y_pred2=fitted2.predict(iris.data)
confusion_matrix(iris.target,y_pred2)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0, 14, 36]], dtype=int64)

# 2. Multinomial naive bayes

- 모듈 불러오기 및 데이터 생성

In [14]:
from sklearn.naive_bayes import MultinomialNB

In [15]:
import numpy as np

In [16]:
X = np.random.randint(5, size=(6, 100)) #변수가 100개고 샘플의 갯수가 6개인 상황
y = np.array([1, 2, 3, 4, 5, 6]) #y 6개

In [17]:
X
#통계적으로는 피팅이 불가능이지만 나이브베이즈는 가능

array([[0, 4, 0, 2, 3, 3, 4, 0, 2, 0, 1, 2, 2, 1, 4, 0, 1, 3, 0, 3, 3, 2,
        3, 2, 2, 4, 3, 2, 0, 1, 4, 2, 4, 3, 4, 4, 0, 4, 4, 2, 1, 2, 0, 3,
        4, 4, 4, 2, 4, 0, 0, 1, 2, 1, 2, 1, 3, 2, 0, 0, 4, 4, 1, 1, 3, 0,
        1, 0, 1, 3, 0, 1, 1, 1, 3, 3, 2, 2, 1, 2, 0, 2, 0, 3, 2, 2, 3, 1,
        3, 0, 0, 1, 2, 1, 1, 1, 3, 1, 2, 3],
       [1, 1, 4, 2, 0, 1, 2, 4, 3, 4, 3, 4, 2, 4, 4, 0, 0, 0, 3, 3, 3, 0,
        4, 4, 2, 3, 4, 4, 1, 1, 1, 1, 4, 3, 1, 4, 1, 3, 0, 1, 3, 3, 0, 1,
        3, 3, 0, 2, 1, 3, 4, 1, 3, 2, 4, 2, 4, 1, 4, 4, 1, 1, 3, 4, 4, 3,
        0, 0, 2, 2, 4, 0, 0, 4, 4, 3, 2, 1, 4, 3, 2, 3, 1, 1, 1, 4, 4, 0,
        0, 2, 1, 3, 3, 1, 2, 0, 2, 2, 2, 4],
       [1, 4, 3, 1, 0, 2, 4, 1, 3, 1, 3, 4, 3, 0, 3, 2, 2, 1, 2, 1, 3, 0,
        3, 1, 2, 4, 2, 1, 2, 3, 4, 3, 0, 0, 3, 3, 0, 1, 0, 1, 2, 0, 1, 3,
        1, 1, 1, 2, 4, 0, 0, 1, 2, 4, 3, 4, 0, 3, 3, 4, 1, 2, 0, 2, 2, 3,
        0, 3, 4, 3, 2, 1, 1, 2, 0, 1, 2, 3, 2, 3, 4, 0, 4, 4, 0, 0, 0, 3,
        2, 1, 2, 4, 4,

In [18]:
y

array([1, 2, 3, 4, 5, 6])

- Multinomial naive bayes 모델 생성

In [19]:
clf = MultinomialNB()
clf.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [20]:
print(clf.predict(X[2:3]))#2번째 관측치를 예측했을때 3으로 결과가 나온다

[3]


In [21]:
clf.predict_proba(X[2:3])

array([[2.01967798e-33, 2.82488645e-30, 1.00000000e+00, 4.10259204e-32,
        6.78681030e-40, 4.09277227e-33]])

- prior 변경해보기

In [22]:
clf2 = MultinomialNB(class_prior=[0.1,0.1999,0.0001,0.1,0.1,0.1])
clf2.fit(X, y)
#두번쨰 범주의 확률만 높음

MultinomialNB(alpha=1.0, class_prior=[0.1, 0.1999, 0.0001, 0.1, 0.1, 0.1],
              fit_prior=True)

In [23]:
clf2.predict_proba(X[2:3])
#prior를 높게준 범주의 확률이 높아짐

array([[2.01967798e-30, 5.64694801e-27, 1.00000000e+00, 4.10259204e-29,
        6.78681030e-37, 4.09277227e-30]])